[package]
name = "spaceman-dmm"
version = "0.1.0"
authors = ["Tad Hardesty <tad@platymuus.com>"]

[[bin]]
name = "editor"
path = "main.rs"

[dependencies]
same-file = "1.0.0"
toml = "0.4.5"
serde = "1.0.21"
serde_derive = "1.0.21"
dreammaker = { path = "../dreammaker" }
dmm-tools = { path = "../tools" }
qt-extras = { path = "../qt-extras" }

[dependencies.glium]
default-features = false
version = "0.18.1"
